### ISSUE TITLE
Meta-issue: create a plan

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/cpython#2]
Tentatively the plan could just be:

- [ ] Add a non-functional command-line flag that can enable and disable the new parser
- [ ] Add a `PYTHON{SOMETHING}` env variable to do the same
- [ ] Add an API that invokes the new parser explicitly (and another that invokes the old parser)
- [ ] Make the flag have the desired effect

**Comment by gvanrossum** [comment]
Each plan item could be tracked by a separate issue, or on the Project board (though I have no experience using that GitHub feature).

**Comment by gvanrossum** [comment]
I think we have enough issues to represent the plan now.
